import type { Metadata } from "next"
import { Sora } from "next/font/google"
import "../styles/globals.css"
import { Navigation } from "@/components/organisms/navigation"

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Digital Agency Portfolio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased`}>
        <div className="bg-stone-950 flex flex-col justify-between min-h-screen">
          <Navigation />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  )
}
