import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "../styles/globals.css";
import { Navigation } from "@/components/organisms/navigation";
import { Footer } from "@/components/organisms/footer";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Agency Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased`}>
        <div className="flex min-h-screen flex-col justify-between bg-stone-950">
          <Navigation />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
